### ISSUE TITLE
WhatTheStack does not capture very early crashes

### ISSUE THREAD

**Issue by matejdro** [haroldadmin/WhatTheStack#28] opened 2021-11-29 09:09 UTC
For example, crash in MainActivity's `onCreate` method will not be captured.

**Comment by haroldadmin** [comment] 2021-11-29 11:49
Duplicate of #3.

Unfortunately this is not an easily fixable problem. I would welcome ideas/fixes to resolve this though!

**Comment by haroldadmin** [comment] 2021-11-29 11:49
Closing this issue in favour of #3. Let's keep the discussion in that thread.

**Closed as completed by haroldadmin** 2021-11-29 11:49 UTC
